# fly.toml app configuration file generated for whereis-api-v0 on 2025-04-07T22:15:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whereis-api-v0'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
