# fly.toml app configuration file generated for whereis-api-v0 on 2025-04-07T22:15:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whereis-api-v0'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.web_health]
    grace_period = "30s"
    interval = "5s"
    method = "get"
    path = "/web-health"
    port = 8080
    timeout = "2s"
    type = "http"
  [checks.app_health]
    grace_period = "30s"
    interval = "10s"
    method = "get"
    path = "/app-health"
    port = 8080
    timeout = "5s"
    type = "http"
